
import java.awt.BorderLayout;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author inuya
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        setUndecorated(true);
        initComponents();
        Contenido.setLayout(new BorderLayout());
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        
        Principal Prin = new Principal();
        
        Contenido.removeAll();
        Contenido.add(Prin, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Principal = new javax.swing.JButton();
        Ventas = new javax.swing.JButton();
        Inventario = new javax.swing.JButton();
        Productos = new javax.swing.JButton();
        Reportes = new javax.swing.JButton();
        Acerca_de = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1900, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(810, 550));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        getContentPane().add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1340, 870));

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setPreferredSize(new java.awt.Dimension(275, 550));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STOP JEANS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 157, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 20));

        Menu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 202, -1));

        Principal.setBackground(new java.awt.Color(51, 51, 51));
        Principal.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Principal.setForeground(new java.awt.Color(255, 255, 255));
        Principal.setText("🏠 Principal");
        Principal.setBorderPainted(false);
        Principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrincipalActionPerformed(evt);
            }
        });
        Menu.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        Ventas.setBackground(new java.awt.Color(51, 51, 51));
        Ventas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Ventas.setForeground(new java.awt.Color(255, 255, 255));
        Ventas.setText("🛒 Ventas");
        Ventas.setBorderPainted(false);
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        Menu.add(Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 50));

        Inventario.setBackground(new java.awt.Color(51, 51, 51));
        Inventario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Inventario.setForeground(new java.awt.Color(255, 255, 255));
        Inventario.setText("📦 Inventario");
        Inventario.setBorderPainted(false);
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        Menu.add(Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 50));

        Productos.setBackground(new java.awt.Color(51, 51, 51));
        Productos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Productos.setForeground(new java.awt.Color(255, 255, 255));
        Productos.setText("👕 Productos");
        Productos.setBorderPainted(false);
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        Menu.add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 50));

        Reportes.setBackground(new java.awt.Color(51, 51, 51));
        Reportes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Reportes.setForeground(new java.awt.Color(255, 255, 255));
        Reportes.setText("📊 Reportes");
        Reportes.setBorderPainted(false);
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });
        Menu.add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 50));

        Acerca_de.setBackground(new java.awt.Color(0, 0, 0));
        Acerca_de.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Acerca_de.setForeground(new java.awt.Color(255, 255, 255));
        Acerca_de.setText("Ⓘ Acerca de");
        Acerca_de.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Acerca_de.setBorderPainted(false);
        Acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acerca_deActionPerformed(evt);
            }
        });
        Menu.add(Acerca_de, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 220, 50));

        Salir.setBackground(new java.awt.Color(0, 0, 0));
        Salir.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir\n");
        Salir.setBorder(null);
        Salir.setBorderPainted(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Menu.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 220, 50));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
       Ventas Ven = new Ventas();
        
        Contenido.removeAll();
        Contenido.add(Ven, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_VentasActionPerformed

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
       Inventario Inv = new Inventario();
        
        Contenido.removeAll();
        Contenido.add(Inv, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_InventarioActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        Productos Pro = new Productos();
        
        Contenido.removeAll();
        Contenido.add(Pro, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_ProductosActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        Reportes Re = new Reportes();
        
        Contenido.removeAll();
        Contenido.add(Re, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_ReportesActionPerformed

    private void Acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acerca_deActionPerformed
        Acerca_de Ac = new Acerca_de();
        
        Contenido.removeAll();
        Contenido.add(Ac, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_Acerca_deActionPerformed

    private void PrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrincipalActionPerformed
        Principal Prin = new Principal();

        Contenido.removeAll();
        Contenido.add(Prin, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }//GEN-LAST:event_PrincipalActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acerca_de;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton Inventario;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Principal;
    private javax.swing.JButton Productos;
    private javax.swing.JButton Reportes;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
